### ISSUE TITLE
File Paths is not right

### ISSUE THREAD

**Issue by utzerath** [RESHAPELab/ART-UI#1]
When adding a str that is the file path to externaldatabase instance, the file cannot be found even though the file path seems to be correct. Where is it looking for files?

**Comment by BenCarter44** [comment]
The working directory of the whole repository when the web server is run is `/AST_Rock_Website` where repo is root.

So, to get the databases and domains, one can refer to the files from the working directory like this:
``` python

db = DatabaseManager(
        dbfile="CoreEngine/output/main.db",
        cachefile="CoreEngine/output/ai_result_backup.db",
        label_file="CoreEngine/data/subdomain_labels.json",
    )
```
